# Generated by Django 2.2.7 on 2019-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='progress',
        ),
        migrations.AddField(
            model_name='user',
            name='step',
            field=models.TextField(default='first_expression'),
        ),
    ]
