# Generated by Django 2.2.7 on 2019-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191117_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeentry',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
