# Generated by Django 2.2.7 on 2020-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200103_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='developer_mode',
            field=models.BooleanField(default=False),
        ),
    ]
