# Generated by Django 2.2.11 on 2020-08-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200806_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='step_name',
        ),
    ]
