# Generated by Django 2.2.11 on 2020-10-04 21:31

from django.db import migrations


def forwards_func(apps, _schema_editor):
    User = apps.get_model("main", "User")
    for user in User.objects.all():
        user.json["pages_progress"]["FunctionsAndMethodsForLists"] = {"step_name": "append_vs_concatenate"}
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_remove_user_step_name'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
